### ISSUE TITLE
Add package to CRAN or HADES

### ISSUE THREAD

**Issue by egillax** [OHDSI/BrokenAdaptiveRidge#7]
Hi @msuchard ,

Would it be possible to add this package to either CRAN or HADES ? That way we can add this model in the PLP.

Thanks!
Egill

**Comment by msuchard** [comment]
@egillax  -- uhm, I believe `BAR` is both on CRAN and part of HADES.   @schuemie -- did we squash the idea of adding `BAR` to HADES?

**Comment by egillax** [comment]
@msuchard  I can't find it in the HADES [package list](https://ohdsi.github.io/Hades/packages.html). Can neither find it in CRAN.

Although IterativeHardThresholding is in both which you might be thinking of?

**Comment by schuemie** [comment]
@msuchard I don't remember discussing including BAR in HADES. I suspect @egillax is right, and you're thinking of IHT.

**Comment by msuchard** [comment]
Yeah, I suck.  It was `IHT`.   I'll work on `BAR` when I return from vacation.

**Comment by msuchard** [comment]
Am in process of submitting to CRAN.

**Comment by msuchard** [comment]
done. https://cran.r-project.org/web/packages/BrokenAdaptiveRidge/index.html

**Comment by schuemie** [comment]
@msuchard : do you also want this to be in HADES?

**Comment by msuchard** [comment]
@schuemie : sure, if that's an option.  i just added the requisite webpage.  am i missing anything else?

**Comment by schuemie** [comment]
Could you add a NEWS.md, and create at least one GitHub release? I think then we're good to go for HADES inclusion.

**Comment by msuchard** [comment]
done.

**Comment by schuemie** [comment]
Thanks! In HADES now. Could I bother you to announce this new (to HADES) package on the Forums? https://forums.ohdsi.org/t/hades-development-announcements/12293/140

I took the liberty of making the README a little bit more HADES-like, and I regenerated the website. I also updated the GA workflows to HADES standards. I hope you don't mind.
